site_name: Open Cataclysmic Variable Radio Catalog (OCVRC)
site_url: https://jprenderg.github.io/OCVRC/

theme:
  name: material

nav:
  - Home: index.md
  - Catalog Fields: fields.md
  - Downloads: downloads.md
  - Updating the Catalog: updating.md